#!/bin/bash

SLOGAN_SUGGESTIONS=(

    "Ack Storm"
    "Across The Stars"
    "Active Active"
    "Active Passive"
    "Adjoint Prophet"
    "AI Prophet"
    "Alderaan Is Gone"
    "All Systems Red"
    "All Your Base"
    "Anon Spirit"
    "Anycast Nomad"
    "Arc Reactor Heart"
    "Arrows Block Sun"
    "Artifact Keeper"
    "AS Path"
    "Assembler Sage"
    "Assimilate Or Perish"
    "A Star"
    "Async Prophet"
    "Atomic Mage"
    "Automate All"
    "AVL Tree"
    "Await Wizard"
    "Backprop Lord"
    "Backtrack Spirit"
    "Backup Mage"
    "Balance Must Hold"
    "Banana For Scale"
    "Bandwidth Rider"
    "Bellman Ford"
    "Beware Jabberwock My"
    "Beyond The Rim"
    "BFS Rider"
    "BGP Wizard"
    "Bias Buster"
    "Binary Bard"
    "Binary Never Lies"
    "Bit Shifter"
    "Black Ice"
    "Blast Radius"
    "Blockchain Knight"
    "Blood And Chrome"
    "Bloom Filter"
    "Blue Pill"
    "Blue Team Standing"
    "Books Are Portals"
    "Botnet Keeper"
    "Brace For Impact"
    "Branch Bound"
    "Branch Diver"
    "Break Condition"
    "Breakpoint Lord"
    "Broadcast Mage"
    "Bubble Slayer"
    "Bufferbloat Slayer"
    "Buffer Overflow"
    "Bug Hunter"
    "Build Breaker"
    "Build It Break"
    "Bulletproof Spirit"
    "By Your Command"
    "Callback Hell"
    "Call Of Cthulhu"
    "CA Prophet"
    "Captcha Slayer"
    "Cast Fireball Now"
    "Catch Wizard"
    "Category Knight"
    "Certificate Lord"
    "Chaos Engineer"
    "Chaos Ensues Again"
    "Chaos Monkey"
    "Chaos Reigns Supreme"
    "Choose Your Weapon"
    "Chrono Triggered Again"
    "Church Numeral"
    "Cipher Dragon"
    "Clerics Heal All"
    "Cloak And Dagger"
    "Clone Wars Rage"
    "Closed Loop"
    "Cloud Phantom"
    "Cluster Lord"
    "Cluster Sage"
    "Code Is Poetry"
    "Code Like Wind"
    "Codepunk Prophet"
    "Code Wizard"
    "Cold Standby"
    "Colimit Spirit"
    "Commit Sage"
    "Compiler Dragon"
    "Congestion Control"
    "Consensus Rider"
    "Console Cowboy"
    "Container Captain"
    "Content Delivery"
    "Continue Path"
    "Continuous Mage"
    "Cook Levin"
    "Core Dump"
    "Coroutine Rider"
    "Coverage Hunter"
    "Cowboy Bebop Blues"
    "Crack The Code"
    "Critical Failure Looms"
    "Critical Hit Success"
    "CRL Keeper"
    "Crypto Mage"
    "Cthulhu Rises Dreaming"
    "Ctrl Alt Del"
    "Cuckoo Hash"
    "Curry Howard"
    "Cyber Dreamer"
    "Cyberpunk Never Dies"
    "Cyberspace Rider"
    "Daemon Slayer"
    "Daemon Whisperer"
    "DAO Prophet"
    "Darknet Ranger"
    "Dark Side Rising"
    "Data Dreams Awake"
    "Dataset Nomad"
    "Datastream Rider"
    "DDoS Dragon"
    "Deadlock Knight"
    "Debug Druid"
    "Debugging Is Magic"
    "Decrypt The Planet"
    "Deep Dreamer"
    "Dependent Type"
    "Deploy Dragon"
    "DFS Nomad"
    "Dice Decide Fate"
    "Differential Nomad"
    "Diffie Hellman"
    "Dijkstra Rider"
    "Disaster Recovery"
    "Disjoint Set"
    "Divide Conquer"
    "DM Rolls High"
    "DNS Druid"
    "Don’t Panic Towel"
    "Dragons Dream Fire"
    "Dragons Hoard Gold"
    "Dreams Of Electric"
    "Dwarves Mine Deep"
    "Dynamic Sage"
    "Eat Sleep Hack"
    "ECN Knight"
    "Edge Cache"
    "Edge Caster"
    "Elevated Privilege"
    "Elliptic Curve"
    "Elves Sing Eternal"
    "Embrace The Void"
    "Encrypt Or Die"
    "Endian Mage"
    "End Of Line"
    "Endofunctor Mage"
    "Engage Warp Drive"
    "Entropy Always Wins"
    "Entropy Mage"
    "Epoch Rider"
    "Error State"
    "Event Loop"
    "Evil Twin"
    "Exception Sage"
    "Exploit Hunter"
    "Fail Forward Fast"
    "Failover Rider"
    "Failure Injector"
    "Fair Queue"
    "Fallback Keeper"
    "Fault Domain"
    "Fault Tolerant"
    "Fear The Reaper"
    "Feature Wizard"
    "Fiber Nomad"
    "Finally Keeper"
    "Firewall Burns Down"
    "Firewall Slayer"
    "Five Nines"
    "Flow Keeper"
    "Floyd Warshall"
    "Fly You Fools"
    "Force Awakens Now"
    "Forge New Legends"
    "Fork Bomb"
    "Fork Tactician"
    "Fortune Favors Bold"
    "Forward Unto Dawn"
    "Function AsA"
    "Functor Spirit"
    "Future Eats Past"
    "Future Mage"
    "Galaxy In Flames"
    "GAN Rider"
    "Garbage Collected"
    "Gas Oracle"
    "Geo Redundant"
    "Glass Cannon Life"
    "Glitch In Matrix"
    "Gold Solves Problems"
    "Graceful Degrader"
    "Gradient Keeper"
    "Graph Knight"
    "Great Old Ones"
    "Greedy Prophet"
    "Gremlin Rider"
    "GRE Spirit"
    "Hackers Unite Tonight"
    "Hallucination Mage"
    "Handshake Keeper"
    "Han Shot First"
    "Hash Cracker"
    "Hash Lord"
    "Heap Master"
    "Heap Sort"
    "Hello World"
    "Hex Lord"
    "High Availability"
    "Homomorphic Mage"
    "Hope Survives Always"
    "Hotfix Healer"
    "Hot Standby"
    "HTTP Bard"
    "Ice Breaker"
    "Imagination Runs Wild"
    "Immortal Coil Awakens"
    "Incremental Spirit"
    "Infinite Loop"
    "Infinity Stones Gather"
    "In Rust Trust"
    "Insertion Rider"
    "Integration Spirit"
    "Interpreter Spirit"
    "Interrupt Lord"
    "IP Hunter"
    "IPSec Mage"
    "ISR Prophet"
    "IV Shaman"
    "IXP Keeper"
    "Jitter Spirit"
    "Kan Extension"
    "Kernel Panic"
    "Key Exchange"
    "Key Master"
    "Knowledge Is Power"
    "Kosaraju Keeper"
    "Kruskal Rider"
    "Kubernetes Knight"
    "Label Keeper"
    "Lambda Calculus"
    "Lambda Wizard"
    "Latency Dragon"
    "Latency Slayer"
    "Leaky Bucket"
    "Ledger Mage"
    "Legend Lives On"
    "Librarians Save Worlds"
    "Lightcycle Chase Begins"
    "Limit Keeper"
    "Linker Goblin"
    "Livelock Rider"
    "Live Long Prosper"
    "Load Balancer"
    "Loader Elf"
    "Logic Gatekeeper"
    "Loss Function"
    "Lost In Transmission"
    "Lost Time Travelers"
    "Machines Have Souls"
    "Madness Takes Hold"
    "Magic Always Costs"
    "Magic Missile Cast"
    "Magic Numbers"
    "Mainframe Ghost"
    "Malware Druid"
    "Man InMiddle"
    "Master Control Program"
    "Matrix Walker"
    "Meltdown Mage"
    "Memory Leak"
    "Merge Conflict"
    "Merge Sort"
    "Merkle Keeper"
    "Mind Over Matter"
    "Miner Spirit"
    "Mock Object"
    "Monad Rider"
    "Multicast Rider"
    "Multiverse Collides Again"
    "Mutex Keeper"
    "Natural Transform"
    "Natural Twenty Saves"
    "Necromancers Raise Dead"
    "Neon Lights Fade"
    "Net Neutral"
    "Neural Knight"
    "Neuromancer Spirit"
    "Never Split Party"
    "Nonce Rider"
    "NP Hard"
    "Null Pointer"
    "Obey Giant Robot"
    "Obfuscation Lord"
    "Observer Spirit"
    "OCSP Spirit"
    "Octal Druid"
    "One Does Not"
    "Onion Knight"
    "Opcode Prophet"
    "Open Source"
    "OpenVPN Knight"
    "Optimizer Spirit"
    "Orchestrator Sage"
    "Orcs March On"
    "Order Must Stand"
    "Outlaws Ride Free"
    "Overfit Slayer"
    "Overlay Keeper"
    "Packet Cowboy"
    "Packet Loss"
    "Packet Sniffer"
    "Paillier Rider"
    "Paladins Smite Evil"
    "Paradox Destroys All"
    "Parsec Kessel Run"
    "Party Never Split"
    "Past Shapes Future"
    "Patch Paladin"
    "Patricia Rider"
    "Payload Prophet"
    "Peering Prophet"
    "P Equal NP"
    "Phasers On Stun"
    "Phish Knight"
    "Pipeline Rider"
    "Player Agency Matters"
    "Pod Keeper"
    "Policer Rider"
    "Port Hacker"
    "Post Quantum"
    "Power Corrupts Absolutely"
    "Prefix Spirit"
    "Prim Nomad"
    "Privilege Escalation"
    "PRNG Prophet"
    "Program Or Be"
    "Promise Keeper"
    "Prompt Whisperer"
    "Protocol Prophet"
    "Proxy Phantom"
    "Publisher Knight"
    "Pullback Rider"
    "Pull Wizard"
    "Push Master"
    "Pushout Mage"
    "QoS Dragon"
    "Quantum Breaker"
    "Quantum Coder"
    "Quest Givers Lie"
    "Question All Things"
    "Queue Depth"
    "Quick Sort"
    "Race Condition"
    "Radix Spirit"
    "Rainbow Table"
    "Rebase Ranger"
    "Rebellion Never Dies"
    "Red Black"
    "RED Mage"
    "Red Pill"
    "Red Team Rising"
    "Regex Knight"
    "Regression Slayer"
    "Release Mage"
    "Replay Attack"
    "Replicators Gone Wild"
    "Resilience Knight"
    "Resistance Is Futile"
    "Restore Wizard"
    "Retro Future Bright"
    "Retry Mage"
    "Revocation Rider"
    "Ride Eternal Shiny"
    "Ring Signature"
    "Roko Basilisk"
    "Roll For Initiative"
    "Roll Natural Twenty"
    "Root Access"
    "Rootkit Rider"
    "Route Flap"
    "Rowhammer Rider"
    "RSA Nomad"
    "Run All"
    "Runtime Error"
    "Salt Keeper"
    "Sanity Points Lost"
    "SAT Solver"
    "Save Versus Death"
    "SCC Rider"
    "Secret Wars Loom"
    "Seed Spirit"
    "Seek Strange Aeons"
    "Segfault Rider"
    "Selection Keeper"
    "Semantic Sage"
    "Semaphore Spirit"
    "Serverless Spirit"
    "Service Mesh"
    "Session Zero Matters"
    "Set Phasers Kill"
    "Shadowrun Never Ends"
    "Shadows Have Teeth"
    "Shaper Spirit"
    "Shellcode Sage"
    "Shell Ninja"
    "Shields Up Captain"
    "Side Channel"
    "Signal Handler"
    "Signature Sage"
    "Silence Is Root"
    "SimStim Dreamer"
    "Singularity Knight"
    "Skip List"
    "Skulls For Throne"
    "Slay The Dragon"
    "Smart Contract"
    "SMT Rider"
    "Snake Eats Tail"
    "Snapshot Keeper"
    "Socket Sorcerer"
    "Source Keeper"
    "Spam Lord"
    "Spartan Lives Forever"
    "Speak Friend Enter"
    "Spectre Spirit"
    "Spice Must Flow"
    "Spider Verse Forever"
    "SSL Shaman"
    "Stack Overflow"
    "Star Destroyer Approaches"
    "Step Overlord"
    "Subscriber Rider"
    "Syntax Sorcerer"
    "System Shaper"
    "System Shock Rising"
    "Tabletop Forever Bound"
    "Tag Prophet"
    "Tail Drop"
    "Tank Beats Everything"
    "Tarjan Spirit"
    "TCP Knight"
    "Techno Shaman"
    "Techno Shaman Dreaming"
    "Test Driven"
    "Theorem Prover"
    "Thread Lord"
    "Throughput Knight"
    "Throughput Lord"
    "Through The Lookingglass"
    "Throw Dragon"
    "Time Heals Nothing"
    "Timelines Collide Hard"
    "Timeout Slayer"
    "Timing Leak"
    "TLS Paladin"
    "TLS Rider"
    "Token Bucket"
    "Token Keeper"
    "Toposort Mage"
    "Tor Mage"
    "Trace Walker"
    "Transit Rider"
    "Trie Mage"
    "Trojan Horse"
    "Trust No One"
    "Try Spirit"
    "Tunnel Dragon"
    "Turing Test Passed"
    "Type Theory"
    "UDP Nomad"
    "Unicast Knight"
    "Union Find"
    "Unit Tester"
    "User Has Control"
    "Variance Spirit"
    "Version Keeper"
    "Virus Spirit"
    "Void Between Stars"
    "VXLAN Rider"
    "Wallet Wizard"
    "Warlocks Pact Bound"
    "While True"
    "White Rabbit"
    "Who Watches Watchmen"
    "Window Scaling"
    "Winter Is Coming"
    "Wireguard Nomad"
    "Wizard Behind Curtain"
    "Worm Rider"
    "Y Combinator"
    "Yoneda Lemma"
    "Zero Day"
    "Zion Coder"
    "ZK Proof"
    "Zombie Process"
)

STYLE_SUGGESTIONS=(
    "Abstract Expressionism"
    "African Tribal"
    "Afrofuturism"
    "Alien Biome"
    "Ancient Egyptian"
    "Art Deco"
    "Art Nouveau Architecture"
    "Art Nouveau"
    "Arts and Crafts Movement"
    "Astro-Gothic"
    "Atompunk"
    "Aztec Codex"
    "Baroque Architecture"
    "Baroque"
    "Bauhaus Design"
    "Bauhaus"
    "Beaux-Arts"
    "Benin Bronzes"
    "Biopunk"
    "Brutalism"
    "Byzantine"
    "Cassette Futurism"
    "Cave Painting"
    "Celtic Art"
    "Chinese Ink Painting"
    "Classical Architecture"
    "Colonial Revival"
    "Color Field"
    "Conceptual Art"
    "Constructivism"
    "Contemporary"
    "Cottagecore"
    "Cubism"
    "Cyberpunk"
    "Dada"
    "Dark Academia"
    "Dark Fantasy"
    "De Stijl"
    "Deconstructivism"
    "Decopunk"
    "Dieselpunk"
    "Dreamcore"
    "Dystopian"
    "Escheresque"
    "Esoteric Symbolism"
    "Ethiopian Christian Iconography"
    "Expressionism"
    "Fairycore"
    "Fauvism"
    "Futurism"
    "Futurist Architecture"
    "Glitch Art"
    "Goblincore"
    "Googie Architecture"
    "Gothic Architecture"
    "Gothic Revival"
    "Gothic"
    "Graffiti"
    "Greek Classical"
    "Greek Revival"
    "Grimdark"
    "Hellenistic"
    "High Fantasy"
    "High Renaissance"
    "High-Tech Architecture"
    "Impressionism"
    "Inca Art"
    "Indigenous Australian Dot Painting"
    "Installation Art"
    "International Style"
    "Islamic Geometric"
    "Japanese Sumi-e"
    "Japanese Ukiyo-e"
    "Kaiju"
    "Korean Minhwa"
    "Light Academia"
    "Liminal"
    "Lovecraftian"
    "Low Poly"
    "Lunarpunk"
    "Mannerism"
    "Maori Carving"
    "Mayan Art"
    "Mecha"
    "Mesopotamian"
    "Metabolist Architecture"
    "Minimalism"
    "Minimalist Design"
    "Mongolian Art"
    "Mughal Miniature"
    "Mythpunk"
    "Nanopunk"
    "Native American Ledger Art"
    "Neoclassical Architecture"
    "Neoclassicism"
    "Neon Noir"
    "Occult Aesthetic"
    "Op Art"
    "Organic Architecture"
    "Otherworldly Architecture"
    "Outsider Art"
    "Parametric Design"
    "Performance Art"
    "Persian Miniature"
    "Petroglyph"
    "Photorealism"
    "Pixel Art"
    "Polynesian Tatau"
    "Pop Art"
    "Post-Apocalyptic"
    "Post-Impressionism"
    "Postmodern Architecture"
    "Pre-Columbian Mesoamerican"
    "Prehistoric"
    "Psychedelic"
    "Rajput Painting"
    "Realism"
    "Renaissance Architecture"
    "Renaissance"
    "Retro Horror"
    "Retrofuturism"
    "Rococo Architecture"
    "Rococo"
    "Roman Revival"
    "Roman"
    "Romanesque Architecture"
    "Romanesque"
    "Romanticism"
    "Sacred Geometry"
    "Science Fantasy"
    "Shamanic Visionary"
    "Shan Shui"
    "Solar Opera"
    "Solarpunk"
    "Space Opera"
    "Splatterpunk"
    "Steampunk"
    "Streamline Moderne"
    "Street Art"
    "Suprematism"
    "Surrealism"
    "Sword and Sorcery"
    "Symbolism"
    "Synthwave"
    "Tibetan Thangka"
    "Urban Fantasy"
    "Utopian"
    "Vaporwave"
    "Vernacular Architecture"
    "Visionary Art"
    "Weirdcore"
    "Witchcore"
    "Zombie Apocalypse"
)

MOTIF_SUGGESTIONS=(
    "ancient coin hoard"
    "ancient cracked mask"
    "ancient runes on stone"
    "angel statue cracked"
    "beacon in wasteland"
    "bioluminescent forest path"
    "bird made of fire"
    "bird of smoke"
    "black hole horizon"
    "black sun eclipse"
    "blood-red moon"
    "bone throne"
    "bridge across planets"
    "bridge of bones"
    "bridge of light"
    "broken stained glass"
    "burning candles"
    "burning phoenix feathers"
    "candlelit crypt"
    "carved dragon pillar"
    "castle on cliff"
    "cathedral made of ice"
    "chained floating rock"
    "circuitry embedded stone"
    "clock tower storm"
    "clockwork bird in flight"
    "clockwork serpent"
    "clouds shaped like whales"
    "colossal chessboard"
    "colossal humanoid shadow"
    "colossal tree roots"
    "columns of fire"
    "cosmic desert caravan"
    "cosmic hourglass"
    "cosmic jellyfish swarm"
    "cosmic lotus"
    "cracked planet core"
    "crimson desert sky"
    "crystalline cave interior"
    "desert wind spirits"
    "desert with aurora"
    "desert with giant bones"
    "dragon bones desert"
    "dragon carved cliff"
    "dragon curled mountain"
    "dragon curled tree"
    "drifting data stream"
    "drifting ghost lanterns"
    "drifting origami boats"
    "drifting umbrellas"
    "endless bookshelves"
    "endless chain links"
    "endless spiral staircase"
    "eternal burning tree"
    "flaming sword in stone"
    "floating crystal obelisk"
    "floating feathers"
    "floating iron cubes"
    "floating islands chain"
    "floating paper lanterns"
    "floating rune stones"
    "floating temple above sea"
    "flock of gears"
    "flock of origami"
    "flowering obsidian"
    "flower of glass"
    "forest of swords"
    "forest with glowing eyes"
    "forest with waterfalls"
    "fractal snowflakes"
    "fractured glass planet"
    "fractured hologram face"
    "frozen lighthouse beacon"
    "frozen ocean waves"
    "frozen throne"
    "frozen waterfall palace"
    "futuristic city spire"
    "garden of crystals"
    "garden of glass"
    "garden of statues"
    "gate of fire"
    "gears within mountain"
    "ghost ship sails"
    "giant crystal hand"
    "giant hourglass sands"
    "giant serpent coil"
    "giant stone hands"
    "gilded throne"
    "glitching digital face"
    "glowing cyberpunk skyline"
    "glowing fractal vortex"
    "glowing iron crown"
    "glowing magic sigil"
    "glowing mushrooms"
    "glowing serpent coils"
    "glowing sword hilt"
    "golden circuitry veins"
    "golden labyrinth corridors"
    "golden scarab swarm"
    "hand holding lightning"
    "haunted mirror frame"
    "iron fortress gate"
    "labyrinthine circuitry"
    "lantern-lit cavern"
    "lantern-lit fog"
    "lanterns in snow"
    "lightning split tower"
    "machine-heart fusion"
    "maze of mirrors"
    "mechanical dragonfly wings"
    "mechanical lotus bloom"
    "mechanical raven eye"
    "mechanical rose"
    "mechanical spider nest"
    "mechanical whale breach"
    "meteor shower desert"
    "mirrored forest"
    "mirror-faced statues"
    "molten crystal cavern"
    "molten gold statue"
    "molten iron river"
    "molten lava flow"
    "mountain of skulls"
    "mountain with halo"
    "neon koi fish"
    "neon samurai duel"
    "oasis in wasteland"
    "ocean with floating lanterns"
    "orbital ring city"
    "orbital station wreckage"
    "orb of stormlight"
    "orb of water"
    "owl with galaxy eyes"
    "painted mask fragments"
    "petrified wooden giant"
    "plague doctor mask"
    "portal in forest"
    "pyramid of shifting sand"
    "rainbow over ruins"
    "rain over neon alley"
    "ring of fire"
    "river of stars"
    "robot with vines"
    "roots of planet"
    "ruined cathedral roof"
    "runes in fire"
    "rusted spaceship wreck"
    "serpent eating stars"
    "shattered glass crown"
    "shattered golden mask"
    "shattered moon horizon"
    "shimmering desert mirage"
    "ship caught storm"
    "ship sailing through sky"
    "skull-shaped mountain"
    "sky filled with eyes"
    "sky full of balloons"
    "skyline made of roots"
    "sky torn apart"
    "spiderweb with dew"
    "spilled cosmic ink"
    "spinning cube temple"
    "spiral galaxy swirl"
    "spiraling aurora"
    "spiraling DNA strands"
    "spiraling glass shards"
    "spiraling tornado lightning"
    "spiral nebula bloom"
    "spiral of wings"
    "spiral staircase sky"
    "sprawling fungus forest"
    "stairway into abyss"
    "starfield through branches"
    "star-lit canyon"
    "starry ocean surface"
    "stars bleeding sky"
    "storm above pyramid"
    "storm around dark tower"
    "storm-lashed lighthouse"
    "sunken clock tower"
    "sunken library ruins"
    "sunset clock face"
    "swarm of ravens"
    "swirling ink clouds"
    "temple beneath waves"
    "temple carved mountain"
    "temple of mirrors"
    "tentacled clockwork beast"
    "tentacles from portal"
    "tower of books"
    "tower of gears"
    "tower of skulls"
    "tower of tangled vines"
    "tree growing through skull"
    "tree made of glass"
    "trees with lanterns"
    "twin suns horizon"
    "twisted spire tower"
    "veil of aurora"
    "void doorway"
    "volcanic dragon eruption"
    "volcano beneath sea"
    "whale above clouds"
    "winged mechanical lion"
)

get_text() {
    local prompt="$1"
    local -a suggestions
    # Check if prompt contains the word "slogans"
    if [[ "$prompt" == *"slogans"* ]]; then
        suggestions=("${SLOGAN_SUGGESTIONS[@]}")
        elif [[ "$prompt" == *"styles"* ]]; then
        suggestions=("${STYLE_SUGGESTIONS[@]}")
        elif [[ "$prompt" == *"motif"* ]]; then
        suggestions=("${MOTIF_SUGGESTIONS[@]}")
    else
        suggestions=("unknown")
    fi


    local random_index=$((RANDOM % ${#suggestions[@]}))
    echo "${suggestions[$random_index]}"
}
